name: magic_starter
description: Starter kit for Magic Framework. Auth, Profile, Teams out of the box.
version: 0.0.1
homepage: https://magic.fluttersdk.com
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  magic:
    path: ../magic
  magic_cli:
    path: ../magic/plugins/magic_cli
  url_launcher: ^6.3.0
  args: ^2.7.0
  magic_notifications:
    path: ../magic_notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  flutter_lints: ^6.0.0

executables:
  magic_starter: magic_starter

flutter:
  assets:
    - assets/stubs/install/
