/// **Semantic Token Alias Convention**
///
/// [MagicStarterTokens] provides the default light+dark alias map for the
/// magic_starter component system. Every component resolves colors through
/// these semantic role names rather than palette utilities directly, so a
/// single `DESIGN.md` override (generated by `design:sync`) can re-skin the
/// entire starter kit without touching component code.
///
/// ## Alias Key Convention
///
/// Alias keys follow the CSS-property-prefix convention:
///
/// - **Background roles** use `bg-{role}`: `bg-surface`, `bg-primary`,
///   `bg-destructive`, etc. A component writes `className: 'bg-surface p-4'`
///   and the alias expander replaces the bare `bg-surface` token before the
///   wind parser sees it.
/// - **Text / foreground roles** use `text-{role}`: `text-fg`, `text-fg-muted`,
///   `text-on-primary`, etc.
/// - **Border color roles** use `border-color-{role}`: `border-color-border`,
///   `border-color-border-subtle`. Note: the bare `border` Tailwind utility
///   (add a 1 px border) is separate and unaffected.
///
/// ## Alias Values
///
/// Each value is a wind className string containing exactly two tokens:
///
/// - one bare palette utility (applied in **light** mode), and
/// - one `dark:`-prefixed palette utility (applied in **dark** mode).
///
/// Example: `'bg-white dark:bg-gray-950'`
///
/// The `primary-*` shade references (`bg-primary-600`, `text-primary-600`,
/// etc.) resolve against the consumer-supplied `primary` [MaterialColor] in
/// [WindThemeData.colors] — this map never hardcodes the brand color.
///
/// ## Design:sync Target
///
/// Steps 20-21 (`design:sync`) will later generate a replacement map from a
/// `DESIGN.md` file using arbitrary-hex values
/// (`'bg-[#f9f9ff] dark:bg-[#0f1419]'`). The key set in [defaultAliases] is
/// the **stable contract** that the generated map must satisfy; do not rename
/// keys without coordinating the `design:sync` emitter.
///
/// ## Semantic Roles
///
/// The 17 semantic roles and their key prefixes:
///
/// | Role | Alias key |
/// |------|-----------|
/// | surface | `bg-surface` |
/// | surface-container | `bg-surface-container` |
/// | surface-container-high | `bg-surface-container-high` |
/// | fg | `text-fg` |
/// | fg-muted | `text-fg-muted` |
/// | fg-disabled | `text-fg-disabled` |
/// | primary | `bg-primary` |
/// | on-primary | `text-on-primary` |
/// | primary-container | `bg-primary-container` |
/// | accent | `bg-accent` |
/// | border | `border-color-border` |
/// | border-subtle | `border-color-border-subtle` |
/// | destructive | `bg-destructive` |
/// | on-destructive | `text-on-destructive` |
/// | destructive-container | `bg-destructive-container` |
/// | success | `bg-success` |
/// | warning | `bg-warning` |
///
/// ## Usage
///
/// ```dart
/// final windTheme = WindThemeData(
///   colors: {'primary': myBrandColor},
///   aliases: MagicStarterTokens.defaultAliases,
/// );
/// ```
///
/// In a component:
///
/// ```dart
/// WDiv(
///   className: 'bg-surface text-fg border border-[1px] rounded-lg p-4',
///   child: WText('Hello', className: 'text-fg'),
/// )
/// ```
final class MagicStarterTokens {
  MagicStarterTokens._();

  /// The default semantic alias map providing light+dark token pairs for all
  /// 17 semantic roles used by the magic_starter component system.
  ///
  /// Keys follow the `bg-{role}` / `text-{role}` / `border-color-{role}`
  /// convention so they match the unprefixed tokens used in component
  /// className strings. See the class-level documentation for the full
  /// key-to-role mapping table.
  ///
  /// The `primary-*` shade references resolve against the consumer-supplied
  /// `primary` [MaterialColor] in [WindThemeData.colors]; the brand color is
  /// never hardcoded here.
  static const Map<String, String> defaultAliases = {
    // -- Surface roles (bg- prefix) -----------------------------------------

    /// Main app surface: page and modal backgrounds.
    'bg-surface': 'bg-white dark:bg-gray-950',

    /// Slightly elevated container: cards, panels.
    'bg-surface-container': 'bg-gray-50 dark:bg-gray-900',

    /// More elevated container: nested cards, input backgrounds.
    'bg-surface-container-high': 'bg-gray-100 dark:bg-gray-800',

    // -- Foreground roles (text- prefix) ------------------------------------

    /// Primary body text.
    'text-fg': 'text-gray-900 dark:text-gray-50',

    /// Secondary / muted text: labels, captions.
    'text-fg-muted': 'text-gray-500 dark:text-gray-400',

    /// Disabled text: placeholder, inactive labels.
    'text-fg-disabled': 'text-gray-300 dark:text-gray-600',

    // -- Primary roles ------------------------------------------------------

    /// Primary action background: buttons, active states.
    /// Resolves against the consumer-supplied `primary` color in WindThemeData.
    'bg-primary': 'bg-primary-600 dark:bg-primary-500',

    /// Text / icon on top of the primary background.
    'text-on-primary': 'text-white dark:text-white',

    /// Light tinted container for primary-adjacent surfaces.
    'bg-primary-container': 'bg-primary-100 dark:bg-primary-900',

    // -- Accent role --------------------------------------------------------

    /// Secondary accent background for decorative highlights (default: indigo).
    'bg-accent': 'bg-indigo-600 dark:bg-indigo-500',

    // -- Border color roles (border-color- prefix) --------------------------
    //
    // Note: these control border COLOR only. The `border` / `border-{width}`
    // Tailwind utilities that add border-width are separate bare tokens and
    // are not affected by these aliases.

    /// Default border and divider color.
    'border-color-border': 'border-gray-200 dark:border-gray-700',

    /// Subtle divider, less prominent than `border-color-border`.
    'border-color-border-subtle': 'border-gray-100 dark:border-gray-800',

    // -- Semantic state roles (bg- / text- prefix) --------------------------

    /// Destructive / danger action background.
    'bg-destructive': 'bg-red-600 dark:bg-red-500',

    /// Text / icon on top of the destructive background.
    'text-on-destructive': 'text-white dark:text-white',

    /// Light tinted container for destructive-adjacent surfaces.
    'bg-destructive-container': 'bg-red-100 dark:bg-red-900',

    /// Success / positive confirmation background.
    'bg-success': 'bg-green-600 dark:bg-green-500',

    /// Warning / caution background.
    'bg-warning': 'bg-amber-600 dark:bg-amber-500',
  };
}
