blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/fluttersdk/magic/discussions
    about: Ask questions and discuss Magic plugins with the community
